version: '3'

services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - rag-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
